name: C Program Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Run compiled program
        run: ./build/address_book_tests
